rconsoleprint("@@MAGENTA@@")
rconsolename("FrxWare")
rconsoleprint(" ______       __          __            ")
rconsoleprint("\n")
rconsoleprint("|  ____|      \\ \\        / /            ")
rconsoleprint("\n")
rconsoleprint("| |__ _ ____  _\\ \\  /\\  / /_ _ _ __ ___ ")
rconsoleprint("\n")
rconsoleprint("|  __| '__\\ \\/ /\\ \\/  \\/ / _` | '__/ _ \\ ")
rconsoleprint("\n")
rconsoleprint("| |  | |   >  <  \\  /\\  / (_| | | |  __/")
rconsoleprint("\n")
rconsoleprint("|_|  |_|  /_/\\_\\  \\/  \\/ \\__,_|_|  \\___|")
rconsoleprint("\n")
rconsoleprint("\n")
rconsoleprint("@@GREEN@@")
rconsoleprint("Welcome to Frxware!")
rconsoleprint("\n")
